### ISSUE TITLE
Compile error: nl.armatiek.xslweb.saxon.functions.util.Parse.java

### ISSUE THREAD

**Issue by eluija** [Armatiek/xslweb#2]
When using the latest release for saxon-ee 9.8 (= 9.8.0-15), I have a compile error in the Parse class.
Does this work with release 9.8.0-8 of saxon-ee ? (I can no longer download your version)

nl.armatiek.xslweb.saxon.functions.util.Parse
Error:(64, 51) java: incompatible types: net.sf.saxon.om.ZeroOrOne<net.sf.saxon.om.NodeInfo> cannot be converted to net.sf.saxon.om.NodeInfo

**Comment by maartenkroon** [comment]
@eluija : Since the introduction of the standard XPath extension function "parse-xml()" the function parse() of XSLWeb was internally "wired" to net.sf.saxon.functions.ParseXml.call(). Apparantly the signature of this method changed between version 9.8.0-8 and 9.8.0-15. With the fix in d12a067 both signatures are now supported.
